PREFIX dc: <http://purl.org/dc/elements/1.1/>

select ?code ?conceptURI
where
{
 graph <http://publications.europa.eu/resource/authority/award-criterion-type>
 {
    ?conceptURI dc:identifier ?code .
  }
}