# Required metadata
sonar.projectKey=meaningfy-ws_ted-sws
sonar.organization=meaningfy-ws
sonar.projectName=ted-sws
sonar.projectVersion=0.1.0

# Source directories
sonar.sources=src/ted_sws, src/notebooks, src/infra

# Language
sonar.language=py
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Links
sonar.links.homepage=https://github.com/meaningfy-ws/ted-rdf-conversion-pipeline
sonar.links.scm=https://github.com/meaningfy-ws/ted-rdf-conversion-pipeline
sonar.links.issue=https://github.com/meaningfy-ws/ted-rdf-conversion-pipeline/issues

# Tests
sonar.tests=test

# Exclusions
sonar.exclusions=docs/**/*

# Turn off S100 rule in tests (method naming convention false positives)
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=test/**/*.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S100
sonar.issue.ignore.multicriteria.e2.resourceKey=test/**/*.py
