[tox]
# skipping the setup.py installation/requirement for the moment
skipsdist = true
envlist = py310
#py37,py38,py39,py310 # skipping multiple python distros for the moment


[testenv]
description = Running tests in the corresponding environment
#basepython = /usr/bin/python3.10
passenv = *
commands_pre =
    python -m pip install --upgrade pip setuptools wheel
deps =
    -rrequirements.txt
    -rrequirements.dev.txt
commands =
    {envpython} -m pytest --cov-config=tox.ini


[testenv:unit]
description = Running UNIT tests in the corresponding environment
commands =
    {envpython} -m pytest test/unit

[testenv:features]
commands =
    - {envpython} -m pytest --alluredir=./test/reports/allure/test_results/ ./test/features/
    npx -p allure-commandline allure generate ./test/reports/allure/test_results/ -o ./test/reports/allure/report/ --clean
    allure-combine ./test/reports/allure/report/ --dest ./test/reports/allure/combined_report --remove-temp-files --auto-create-folders
allowlist_externals =
    npx
    allure-combine

[testenv:e2e]
commands =
    {envpython} -m pytest test/e2e

[testenv:cover]
basepython = /usr/bin/python3.10

commands =
    {envpython} -m pytest \
    --cov-report term \
    --cov-report html \
    --cov

[coverage:run]
relative_files = True
source =
    src/ted_sws/
    src/dags/
branch = False


[pytest]
log_cli = true
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S


addopts =
    --cov=src/ted_sws
    --cov=src/dags
    --cov-report=html
    --cov-report=term
    --cov-report=xml
    --junitxml=junit_report.xml
    -r a
    -q
    -v -s
    --gherkin-terminal-reporter
    --disable-pytest-warnings
    --disable-warnings

junit_family=xunit2

testpaths =
    test

[testenv:linter]
deps =
    flake8
    flake8-bugbear
    flake8-builtins
    flake8-comprehensions
    flake8-string-format
    black
    pydocstyle
commands =
    flake8
    black --check .
    pydocstyle