CONCEPTUAL_MAPPINGS_METADATA_SHEET_NAME = "Metadata"
CONCEPTUAL_MAPPINGS_RULES_SHEET_NAME = "Rules"
CONCEPTUAL_MAPPINGS_REMARKS_SHEET_NAME = "Mapping Remarks"
CONCEPTUAL_MAPPINGS_RESOURCES_SHEET_NAME = "Resources"
CONCEPTUAL_MAPPINGS_RML_MODULES_SHEET_NAME = "RML_Modules"
CONCEPTUAL_MAPPINGS_CL1_ROLES_SHEET_NAME = "CL1 Controlled List of Roles"
CONCEPTUAL_MAPPINGS_CL2_ORGANISATIONS_SHEET_NAME = "CL2 Controlled List for Organis"

RULES_E_FORM_BT_NAME = 'eForm BT Name (Provisional/Indicative) (O)'
RULES_FIELD_XPATH = 'Field XPath (M)'
RULES_FIELD_XPATH_CONDITION = 'Field XPath condition (M)'
RULES_SF_FIELD_ID = 'Standard Form Field ID (M)'
RULES_SF_FIELD_NAME = 'Standard Form Field Name (M)'
RULES_E_FORM_BT_ID = 'eForm BT-ID (Provisional/Indicative) (O)'

CL_FIELD_VALUE = 'Field Value (in XML)'
CL_MAPPING_REFERENCE = 'Mapping Reference (in ePO)'
CL_SUPERTYPE = 'SuperType'
CL_XML_PATH_FRAGMENT = 'XML PATH Fragment'
