PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>


select distinct ?code ?conceptURI
where
{
 graph <http://publications.europa.eu/resource/authority/language>
 {

    ?conceptURI skos:notation ?code .

   filter (datatype(?code) in (euvoc:XML_LNG, euvoc:TED_SCHEMA))
#   bind(datatype(?code) as ?datatype)


  }
}