version: 1
task_definition:
  task_execution_role: "ecsTaskExecutionRole"
  task_size:
    mem_limit: 16384
    cpu_limit: 4096
  efs_volumes:
    - name: fuseki-data
      filesystem_id: ${FUSEKI_DATA_VOLUME_ID}
      transit_encryption: ENABLED
  ecs_network_mode: awsvpc
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - $SUBNET_1_ID
        - $SUBNET_2_ID
      security_groups:
        - $SECURITY_GROUP
      assign_public_ip: DISABLED