version: "3"
services:
  metabase:
    environment:
      ENV_MB_DB_TYPE: postgres
      ENV_MB_DB_DBNAME: ${ENV_MB_DB_DBNAME}
      ENV_MB_DB_PORT: ${ENV_MB_DB_PORT}
      ENV_MB_DB_USER: ${ENV_MB_DB_USER}
      ENV_MB_DB_PASS: ${ENV_MB_DB_PASS}
      ENV_MB_DB_HOST: ${ENV_MB_DB_HOST}
      ENV_MB_ENCRYPTION_SECRET_KEY: ${ENV_MB_ENCRYPTION_SECRET_KEY}
    image: ${METABASE_IMAGE_URI}
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/metabase-cli-task
        awslogs-region: ${REGION}
        awslogs-stream-prefix: ecs
    networks:
      ecs-local-network: null
    ports:
    - 3000:3000


networks:
  ecs-local-network:
    external: true
