version: 1
task_definition:
  ecs_network_mode: awsvpc
  efs_volumes:
    - name: mongodb-data
      filesystem_id: ${MONGO_DB_VOLUME_ID}
      transit_encryption: ENABLED
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - $SUBNET_1_ID
        - $SUBNET_2_ID
        - $SUBNET_3_ID
      security_groups:
        - $SECURITY_GROUP
      assign_public_ip: DISABLED