version: "3"
services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    image: public.ecr.aws/g5y4d1v2/meaningfy:mongo
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/mongo-cli-task
        awslogs-region: eu-west-3
        awslogs-stream-prefix: ecs
    networks:
      ecs-local-network: null
    volumes:
      - mongodb-data:/data/db
    ports:
    - 27017:27017
networks:
  ecs-local-network:
    external: true
volumes:
  mongodb-data:
