version: "3"
services:
  mongo-express:
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
    image: ${MONGO_EXPRESS_IMAGE_URI}
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/mongo-express-cli-task
        awslogs-region: eu-west-3
        awslogs-stream-prefix: ecs
    networks:
      ecs-local-network: null
    ports:
    - 8081:8081
networks:
  ecs-local-network:
    external: true
