version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: "ecsTaskExecutionRole"
  task_size:
    mem_limit: 16384
    cpu_limit: 4096
  efs_volumes:
    - name: dags
      filesystem_id: ${DAGS_VOLUME_ID}
      transit_encryption: ENABLED
    - name: logs
      filesystem_id: ${LOGS_VOLUME_ID}
      transit_encryption: ENABLED
    - name: ted_sws
      filesystem_id: ${TED_SWS_VOLUME_ID}
      transit_encryption: ENABLED
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - $SUBNET_1_ID
        - $SUBNET_2_ID
      security_groups:
        - $SECURITY_GROUP
      assign_public_ip: DISABLED