= Event Manager
:description: This page is about Event Manager

Event Manager is designed to handle different types of Event Messages (processes) and log them to different outputs by
using
different Event Handlers.

== Technical usage guide
*SOURCE*: ted_sws.event_manager

The description, full list of parameters and usage hints for every component are documented within the source code.

---

=== Prerequisites

The main component of Event Manager is the Event Logger (_EventLogger_).

EventLogger can be initialized using 1 of 3 Event Handler Configs (_EventHandlerConfig_):
====
- _DAGLoggerConfig_ (to be used specifically for processes in DAG environment)
- _CLILoggerConfig_ (to be used specifically for processes in CLI environment).
- _EventHandlerConfig_ (a generic event handler config)
====

Every _EventHandlerConfig_ manages 3 (any combination of them) of Event Handlers (_EventHandler_):
====
- _EventWriterToConsoleHandler_ (ConsoleHandler)
- _EventWriterToFileHandler_ (FileHandler)
- _EventWriterToMongoDBHandler_ (MongoDBHandler)
====
Default values can be configured using the following environment variables:
[source]
----
DAG_LOGGER_CONFIG_HANDLERS=MongoDBHandler,ConsoleHandler
CLI_LOGGER_CONFIG_HANDLERS=MongoDBHandler,ConsoleHandler,FileHandlers
MONGO_DB_LOGS_DATABASE_NAME=logs_db
LOGGER_LOG_FILENAME=./event_logs/{today}/{hour}/{minute}.log
----

The _EventLogger_ logs (using _EventHandler_ via _EventHandlerConfig_) Event Messages.

EventHandler is responsible for logging Event Messages to specific output.

There are 4 types of Event Messages (_EventMessage_), used for specific events/processes:
====
- _TechnicalEventMessage_ (for technical events/processes)
- _NoticeEventMessage_ (for notice related events/processes)
- _MappingSuiteEventMessage_ (for mapping suite related events/processes)
- _EventMessage_ (for generic events/processes)
====
Every _EventMessage_ type is logged (if MongoDBHandler is used) in separate collection:
====
- _TechnicalEventMessage_ -> *technical_events*
- _NoticeEventMessage_ -> *notice_events*
- _MappingSuiteEventMessage_ -> *mapping_suite_events*
- _EventMessage_ -> *log_events*
====

---
_event_log_ decorator can be used to log the "host" function execution information and/or to inject the event_logger to
be used
inside the function.

---

=== Usage
EventLogger can log EventMessage using different severity levels:
[source]
----
event_logger.debug(event_message)
event_logger.info(event_message)
event_logger.warning(event_message)
event_logger.error(event_message)
----

==== DAG example:
Can be adapted to any function.
====
The @event_log decorator will log a TechnicalEventMessage about the host_function (also including the
execution duration) and will inject the event_logger into dag_context KEYWORD param.
====
[source]
----
from ted_sws.event_manager.adapters.event_log_decorator import event_log
from ted_sws.event_manager.model.event_message import TechnicalEventMessage, NoticeEventMessage
from ted_sws.event_manager.services.logger_from_context import get_logger_from_dag_context, handle_event_message_metadata_dag_context

@event_log(TechnicalEventMessage(title="LOG_MESSAGE_ABOUT_HOST_FUNCTION"))
def host_function(**dag_context)
  # always provide VAR_KEYWORD params (**dag_context or any other name) for event_logger to be injected

  # Extract injected event_logger from dag_context
  event_logger = get_logger_from_dag_context(dag_context)

  event_message = NoticeEventMessage(name="PROCESS_NAME")
  event_message.start_record()  # this will set started_at for logged event message

  context = get_current_context()

  # update event_message metadata with data from dag context (RUN_ID)
  handle_event_message_metadata_dag_context(event_message, "PROCESS_NAME", context)

  event_message.end_record()  # this will set ended_at and duration for logged event message
  event_logger.info(event_message)

----

[source]
----
# just inject the event_logger:
@event_log(is_loggable=False)

# just log the information about "host" function:
@event_log(inject_logger=False)

# specify event_message type to be logged, otherwisee a generic EventMessage will be logged:
@event_log(event_message=NoticeEventMessage(...))
----

[source]
----
from ted_sws.event_manager.adapters.event_handler_config import EventHandlerConfig
from ted_sws.event_manager.adapters.event_logger import EventLogger
from ted_sws.event_manager.adapters.log import ConfigHandlerType

# Initialize a generic event_logger to be used anywhere:
event_logger = EventLogger(EventHandlerConfig(config_handlers=ConfigHandlerType.ConsoleHandler.value))

----

====
All configuration options are described in source code.
====

'''
==== Useful Logging services:
====
from ted_sws.event_manager.services.logger_from_context
====
[source]
----
def get_logger(name: str = None) -> EventLogger:
    """
    This method returns a global (DAG) logger or a custom named DAG logger

    :param name:
    :return:
    """

def get_cli_logger(name: str = None) -> EventLogger:
    """
    This method returns a global (CLI) logger or a custom named CLI logger

    :param name:
    :return:
    """

def get_console_logger(name: str = None) -> EventLogger:
    """
    This method returns a global (console-only) logger or a custom named console-only logger

    :param name:
    :return:
    """

def get_logger_from_dag_context(dag_context: dict) -> EventLogger:
    """
    Get event logger injected into "host" function by event_log decorator.

    :param dag_context: The args that event logger was injected in
    :return: The injected event logger
    """
----
====
from ted_sws.event_manager.services.log
====
[source]
----
def log_info(message: str, name: str = None):
    """
    Logs INFO EventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_error(message: str, name: str = None):
    """
    Logs ERROR EventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_debug(message: str, name: str = None):
    """
    Logs DEBUG EventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_warning(message: str, name: str = None):
    """
    Logs WARNING EventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_technical_info(message: str, name: str = None):
    """
    Logs INFO TechnicalEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_technical_error(message: str, name: str = None):
    """
    Logs ERROR TechnicalEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_technical_debug(message: str, name: str = None):
    """
    Logs DEBUG TechnicalEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_technical_warning(message: str, name: str = None):
    """
    Logs WARNING TechnicalEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_notice_info(message: str, notice_id: str = None, name: str = None):
    """
    Logs INFO NoticeEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param notice_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_notice_error(message: str, notice_id: str = None, name: str = None):
    """
    Logs ERROR NoticeEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param notice_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_notice_debug(message: str, notice_id: str = None, name: str = None):
    """
    Logs DEBUG NoticeEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param notice_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_notice_warning(message: str, notice_id: str = None, name: str = None):
    """
    Logs WARNING NoticeEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param notice_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_mapping_suite_info(message: str, mapping_suite_id: str = None, name: str = None):
    """
    Logs INFO MappingSuiteEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param mapping_suite_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_mapping_suite_error(message: str, mapping_suite_id: str = None, name: str = None):
    """
    Logs ERROR MappingSuiteEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param mapping_suite_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_mapping_suite_debug(message: str, mapping_suite_id: str = None, name: str = None):
    """
    Logs DEBUG MappingSuiteEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param mapping_suite_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_mapping_suite_warning(message: str, mapping_suite_id: str = None, name: str = None):
    """
    Logs WARNING MappingSuiteEventMessage, using global (DAG) logger or a custom named one
    :param message:
    :param mapping_suite_id:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_cli_brief_notice_info(message: str, name: str = None):
    """
    Logs brief (just the message) INFO NoticeEventMessage, using global (CLI) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_cli_brief_notice_error(message: str, name: str = None):
    """
    Logs brief (just the message) ERROR NoticeEventMessage, using global (CLI) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_cli_brief_info(message: str, name: str = None):
    """
    Logs brief (just the message) INFO EventMessage, using global (CLI) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

def log_cli_brief_error(message: str, name: str = None):
    """
    Logs brief (just the message) ERROR EventMessage, using global (CLI) logger or a custom named one
    :param message:
    :param name: Logger name (None to use the global logger)
    :return:
    """

----

===== Logging decorators:
====
from ted_sws.event_manager.adapters.event_log_decorator
====
[source]
----
def event_log(
        event_message: EventMessage = EventMessage(),
        event_handler_config: EventHandlerConfig = DAGLoggerConfig(
            name=DEFAULT_DAG_LOGGER_NAME
        ),
        severity_level: SeverityLevelType = DEFAULT_SEVERITY_LEVEL,
        is_loggable: bool = True,
        inject_logger: bool = True
):
    """
    This is the event_log decorator to be used for method/process logging and event_logger injection.

    :param event_message: The base event message to be logged
    :param event_handler_config: The event handler config for event logger initialization
    :param severity_level: The logging severity level
    :param is_loggable: To log or not to log event message about "host" function
    :param inject_logger: To inject the event logger or not into "host" function
    :return: The decorator wrapper
    """
----
---
