= Event Manager
:description: This page is about Event Manager

Event Manager is designed to handle different types of Event Messages (processes) and log them to different outputs by
using
different Event Handlers.

== Technical usage guide
*SOURCE*: ted_sws.event_manager

The description, full list of parameters and usage hints for every component are documented within the source code.

---

=== Prerequisites

The main component of Event Manager is the Event Logger (_EventLogger_).

EventLogger can be initialized using 1 of 3 Event Handler Configs (_EventHandlerConfig_):
====
- _DAGLoggerConfig_ (to be used specifically for processes in DAG environment)
- _CLILoggerConfig_ (to be used specifically for processes in CLI environment).
- _EventHandlerConfig_ (a generic event handler config)
====

Every _EventHandlerConfig_ manages 3 (any combination of them) of Event Handlers (_EventHandler_):
====
- _EventWriterToConsoleHandler_ (ConsoleHandler)
- _EventWriterToFileHandler_ (FileHandler)
- _EventWriterToMongoDBHandler_ (MongoDBHandler)
====
Default values can be configured using the following environment variables:
[source]
----
DAG_LOGGER_CONFIG_HANDLERS=MongoDBHandler,ConsoleHandler
CLI_LOGGER_CONFIG_HANDLERS=MongoDBHandler,ConsoleHandler,FileHandlers
MONGO_DB_LOGS_DATABASE_NAME=logs_db
LOGGER_LOG_FILENAME=./event_logs/{today}/{hour}/{minute}.log
----

The _EventLogger_ logs (using _EventHandler_ via _EventHandlerConfig_) Event Messages.

EventHandler is responsible for logging Event Messages to specific output.

There are 4 types of Event Messages (_EventMessage_), used for specific events/processes:
====
- _TechnicalEventMessage_ (for technical events/processes)
- _NoticeEventMessage_ (for notice related events/processes)
- _MappingSuiteEventMessage_ (for mapping suite related events/processes)
- _EventMessage_ (for generic events/processes)
====
Every _EventMessage_ type is logged (if MongoDBHandler is used) in separate collections:
====
- _TechnicalEventMessage_ -> *technical_events*
- _NoticeEventMessage_ -> *notice_events*
- _MappingSuiteEventMessage_ -> *mapping_suite_events*
- _EventMessage_ -> *log_events*
====

---
_event_log_ decorator can be used to log the "host" function execution information and/or to inject the event_logger to
be used
inside the function.

---

=== Usage
EventLogger can log EventMessage using different severity levels:
[source]
----
event_logger.debug(event_message)
event_logger.info(event_message)
event_logger.warning(event_message)
event_logger.error(event_message)
----

==== DAG example:
Can be adapted to any function.
====
The @event_log decorator will log a TechnicalEventMessage about the host_function (also including the
execution duration) and will inject the event_logger into dag_context KEYWORD param.
====
[source]
----
from ted_sws.event_manager.adapters.event_log_decorator import event_log
from ted_sws.event_manager.model.event_message import TechnicalEventMessage, NoticeEventMessage
from ted_sws.event_manager.services.logger_from_context import get_logger_from_dag_context, handle_event_message_metadata_dag_context

@event_log(TechnicalEventMessage(title="LOG_MESSAGE_ABOUT_HOST_FUNCTION"))
def host_function(**dag_context)
  # always provide VAR_KEYWORD params (**dag_context or any other name) for event_logger to be injected

  # Extract injected event_logger from dag_context
  event_logger = get_logger_from_dag_context(dag_context)

  event_message = NoticeEventMessage(name="PROCESS_NAME")
  event_message.start_record()  # this will set started_at for logged event message

  context = get_current_context()

  # update event_message metadata with data from dag context (RUN_ID)
  handle_event_message_metadata_dag_context(event_message, "PROCESS_NAME", context)

  event_message.end_record()  # this will set ended_at and duration for logged event message
  event_logger.info(event_message)

----

[source]
----
# just inject the event_logger:
@event_log(is_loggable=False)

# just log the information about "host" function:
@event_log(inject_logger=False)

# specify event_message type to be logged, otherwisee a generic EventMessage will be logged:
@event_log(event_message=NoticeEventMessage(...))
----

[source]
----
from ted_sws.event_manager.adapters.event_handler_config import EventHandlerConfig
from ted_sws.event_manager.adapters.event_logger import EventLogger
from ted_sws.event_manager.adapters.log import ConfigHandlerType

# Initialize a generic event_logger to be used anywhere:
event_logger = EventLogger(EventHandlerConfig(config_handlers=ConfigHandlerType.ConsoleHandler.value))

----

====
All configuration options are described in source code.
====

---
