from datetime import datetime, timedelta

from src.ted_sws.core.model.notice import NoticeStatus


class TEDSWSPipelineDAGException(Exception):
    """

    """


DEFAULT_DAG_ARGUMENTS = {
    "owner": "airflow",
    "depends_on_past": False,
    "start_date": datetime(2022, 1, 1),
    "email": ["info@meaningfy.ws"],
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=3600),
    "execution_timeout": timedelta(days=10),
}

BATCH_SIZE = 2000

XCOM_SOURCE_RUN_TYPE_KEY = "source_run_type"

DAILY_MATERIALISED_VIEWS_DAG_NAME = "daily_materialized_views_update"

NOTICE_PROCESSING_PIPELINE_DAG_MAX_ACTIVE_RUNS = 128
NOTICE_PROCESSING_PIPELINE_DAG_MAX_ACTIVE_TASKS = 128

NOTICE_NORMALISATION_PIPELINE_TASK_ID = "notice_normalisation_pipeline"
NOTICE_TRANSFORMATION_PIPELINE_TASK_ID = "notice_transformation_pipeline"
NOTICE_DISTILLATION_PIPELINE_TASK_ID = "notice_distillation_pipeline"
NOTICE_VALIDATION_PIPELINE_TASK_ID = "notice_validation_pipeline"
NOTICE_PACKAGE_PIPELINE_TASK_ID = "notice_package_pipeline"
NOTICE_PUBLISH_PIPELINE_TASK_ID = "notice_publish_pipeline"
STOP_PROCESSING_TASK_ID = "stop_processing"
BRANCH_SELECTOR_TASK_ID = 'branch_selector'
SELECTOR_BRANCH_BEFORE_TRANSFORMATION_TASK_ID = "switch_to_transformation"
SELECTOR_BRANCH_BEFORE_VALIDATION_TASK_ID = "switch_to_validation"
SELECTOR_BRANCH_BEFORE_PACKAGE_TASK_ID = "switch_to_package"
SELECTOR_BRANCH_BEFORE_PUBLISH_TASK_ID = "switch_to_publish"

BRANCH_SELECTOR_MAP = {NOTICE_NORMALISATION_PIPELINE_TASK_ID: NOTICE_NORMALISATION_PIPELINE_TASK_ID,
                       NOTICE_TRANSFORMATION_PIPELINE_TASK_ID: SELECTOR_BRANCH_BEFORE_TRANSFORMATION_TASK_ID,
                       NOTICE_VALIDATION_PIPELINE_TASK_ID: SELECTOR_BRANCH_BEFORE_VALIDATION_TASK_ID,
                       NOTICE_PACKAGE_PIPELINE_TASK_ID: SELECTOR_BRANCH_BEFORE_PACKAGE_TASK_ID,
                       NOTICE_PUBLISH_PIPELINE_TASK_ID: SELECTOR_BRANCH_BEFORE_PUBLISH_TASK_ID
                       }

START_FROM_NORMALISATION_DAG_PARAM = "start_from_normalisation"
RUN_MATERIALISED_VIEW_DAG_PARAM = "run_materialised_view"
RUN_MATERIALISED_VIEW_DAG_PARAM_DESCRIPTION = "If enabled, triggers the Daily Materialised Views DAG after processing completes."

NOTICE_STATUS_TO_PIPELINE_STEP = {
    NoticeStatus.RAW: NOTICE_NORMALISATION_PIPELINE_TASK_ID,
    NoticeStatus.INDEXED: NOTICE_NORMALISATION_PIPELINE_TASK_ID,
    NoticeStatus.NORMALISED_METADATA: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
    NoticeStatus.INELIGIBLE_FOR_TRANSFORMATION: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
    NoticeStatus.ELIGIBLE_FOR_TRANSFORMATION: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
    NoticeStatus.PREPROCESSED_FOR_TRANSFORMATION: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
    NoticeStatus.TRANSFORMED: NOTICE_DISTILLATION_PIPELINE_TASK_ID,
    NoticeStatus.DISTILLED: NOTICE_VALIDATION_PIPELINE_TASK_ID,
    NoticeStatus.VALIDATED: NOTICE_PACKAGE_PIPELINE_TASK_ID,
    NoticeStatus.INELIGIBLE_FOR_PACKAGING: NOTICE_PACKAGE_PIPELINE_TASK_ID,
    NoticeStatus.ELIGIBLE_FOR_PACKAGING: NOTICE_PACKAGE_PIPELINE_TASK_ID,
    NoticeStatus.PACKAGED: NOTICE_PUBLISH_PIPELINE_TASK_ID,
    NoticeStatus.INELIGIBLE_FOR_PUBLISHING: NOTICE_PUBLISH_PIPELINE_TASK_ID,
    NoticeStatus.ELIGIBLE_FOR_PUBLISHING: NOTICE_PUBLISH_PIPELINE_TASK_ID,
    NoticeStatus.PUBLICLY_UNAVAILABLE: NOTICE_PUBLISH_PIPELINE_TASK_ID,
    NoticeStatus.PUBLICLY_AVAILABLE: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
}

REPROCESS_STATUS_UNNORMALISED = "Unnormalised"
REPROCESS_STATUS_UNVALIDATED = "Unvalidated"
REPROCESS_STATUS_UNTRANSFORMED = "Untransformed"
REPROCESS_STATUS_UNPACKAGED = "Unpackaged"
REPROCESS_STATUS_UNPUBLISHED = "Unpublished"
REPROCESS_STATUS_PUBLISHED = "Published"

REPROCESS_STATUS_DISPLAY_MAP = {
    REPROCESS_STATUS_UNVALIDATED: [
        NoticeStatus.DISTILLED,
    ],
    REPROCESS_STATUS_UNTRANSFORMED: [
        NoticeStatus.NORMALISED_METADATA,
        NoticeStatus.INELIGIBLE_FOR_TRANSFORMATION,
        NoticeStatus.ELIGIBLE_FOR_TRANSFORMATION,
        NoticeStatus.PREPROCESSED_FOR_TRANSFORMATION,
        NoticeStatus.TRANSFORMED,
        NoticeStatus.DISTILLED,
    ],
    REPROCESS_STATUS_UNPUBLISHED: [
        NoticeStatus.ELIGIBLE_FOR_PUBLISHING,
        NoticeStatus.INELIGIBLE_FOR_PUBLISHING,
        NoticeStatus.PACKAGED,
        NoticeStatus.PUBLICLY_UNAVAILABLE,
    ],
    REPROCESS_STATUS_UNPACKAGED: [
        NoticeStatus.VALIDATED,
        NoticeStatus.INELIGIBLE_FOR_PACKAGING,
        NoticeStatus.ELIGIBLE_FOR_PACKAGING,
    ],
    REPROCESS_STATUS_UNNORMALISED: [
        NoticeStatus.RAW,
    ],
    REPROCESS_STATUS_PUBLISHED: [
        NoticeStatus.PUBLICLY_AVAILABLE,
        NoticeStatus.PUBLISHED,
    ]
}

REPROCESS_STATUS_TO_PIPELINE_STEP = {
    REPROCESS_STATUS_UNVALIDATED: NOTICE_VALIDATION_PIPELINE_TASK_ID,
    REPROCESS_STATUS_UNTRANSFORMED: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
    REPROCESS_STATUS_UNPUBLISHED: NOTICE_PUBLISH_PIPELINE_TASK_ID,
    REPROCESS_STATUS_UNPACKAGED: NOTICE_PACKAGE_PIPELINE_TASK_ID,
    REPROCESS_STATUS_UNNORMALISED: NOTICE_NORMALISATION_PIPELINE_TASK_ID,
    REPROCESS_STATUS_PUBLISHED: NOTICE_TRANSFORMATION_PIPELINE_TASK_ID,
}

REPROCESS_STATUS_LIST = [
    REPROCESS_STATUS_UNNORMALISED,
    REPROCESS_STATUS_UNVALIDATED,
    REPROCESS_STATUS_UNTRANSFORMED,
    REPROCESS_STATUS_UNPACKAGED,
    REPROCESS_STATUS_UNPUBLISHED,
    REPROCESS_STATUS_PUBLISHED,
]
