CONCEPTUAL_MAPPINGS_METADATA_SHEET_NAME = "Metadata"
CONCEPTUAL_MAPPINGS_RULES_SHEET_NAME = "Rules"
RULES_E_FORM_BT_NAME = 'eForm BT Name (O)'
RULES_FIELD_XPATH = 'Field XPath (M)'
RULES_SF_FIELD_ID = 'Standard Form Field ID (M)'
RULES_E_FORM_BT_ID = 'eForm BT-ID (O)'

