CONCEPTUAL_MAPPINGS_METADATA_SHEET_NAME = "Metadata"
CONCEPTUAL_MAPPINGS_RULES_SHEET_NAME = "Rules"
CONCEPTUAL_MAPPINGS_RESOURCES_SHEET_NAME = "Resources"
CONCEPTUAL_MAPPINGS_RML_MODULES_SHEET_NAME = "RML_Modules"

RULES_E_FORM_BT_NAME = 'eForm BT Name (Provisional/Indicative) (O)'
RULES_FIELD_XPATH = 'Field XPath (M)'
RULES_SF_FIELD_ID = 'Standard Form Field ID (M)'
RULES_SF_FIELD_NAME = 'Standard Form Field Name (M)'
RULES_E_FORM_BT_ID = 'eForm BT-ID (Provisional/Indicative) (O)'
