prefix epo: <http://data.europa.eu/a4g/ontology#>
prefix rr: <http://www.w3.org/ns/r2rml#>

SELECT distinct ?template ?cls
WHERE {
  values (?tripleMap){
 (<$tripleMapUri>)}


  ?tripleMap a rr:TriplesMap ;
           rr:subjectMap / rr:template ?template ;
       	   rr:subjectMap / rr:class ?cls . 
}
