prefix rml: <http://semweb.mmlab.be/ns/rml#>
prefix rr: <http://www.w3.org/ns/r2rml#>

SELECT ?tripleMap ?source
WHERE {
  values (?tripleMap){
 (<http://data.europa.eu/a4g/mapping/sf-rml/ContactPoint>)}


  ?tripleMap a rr:TriplesMap ;
           rml:logicalSource / rml:source ?source ;
}
