name: Tests on server

on:
  workflow_dispatch:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: pyTest
    runs-on: self-hosted

    steps:
      - run: pwd
      - run: echo One las

      - uses: actions/checkout@v1
      #    - name: Set up Python ${{ matrix.python-version }}
      #      uses: actions/setup-python@v2
      #      with:
      #        python-version: 3.8
      #    - name: Install dependencies
      #      run: |
      #        python -m pip install --upgrade setuptools pip wheel
      #        make install
#      - name: Make envfile
#        uses: SpicyPizza/create-envfile@v1
#        with:
#          envkey_VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
#          envkey_VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
#          envkey_ENVIRONMENT: staging
#          envkey_DOMAIN: ted-data.eu
#          envkey_SUBDOMAIN: staging
#          file_name: .env.staging
      - name: Make envfile
        run: make staging-dotenv-file

      - name: Start staging infra
        run: make start-project-staging-services

      - name: Run unit tests
        run: make test-all
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: coverage.xml
#          env_vars: OS,PYTHON
#          name: codecov-umbrella
#          fail_ci_if_error: true

#      - name: start-infra
#        run: make stop-project-staging-services