name: Tests on hermes server

on:
  workflow_dispatch:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]
env:
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  ENVIRONMENT: staging
jobs:
  build:
    name: pyTest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Make envfile
        run: make staging-dotenv-file

      - name: Get RML mapper
        run: make init-rml-mapper

      - name: Get Saxon
        run: make init-saxon

      - name: Start staging infra
        run: make start-project-services

      - name: Run unit tests
        run: make test-all
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
#      - name: Clean Mongo DB
#        run: make clean-mongo-db
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: coverage.xml
#          env_vars: OS,PYTHON
#          name: codecov-umbrella
#          fail_ci_if_error: true

#      - name: start-infra
#        run: make stop-project-staging-services